### PR TITLE
Grails 3.3 and datastores without refresh support

### PR DESCRIPTION
**Pull request by double16**
Updates fixtures to work with Grails 3.3. This includes handling datastores that do not support the `refresh()` method on domain.

The integration tests do not run because GORM isn't initialized. I can't figure out why. Assistance would be appreciated.

### CODE REVIEW

**Comment by aeischeid** [comment]
Would be really happy to see this plugin working for new version of grails! Thanks for giving it a go!

**Comment by double16** [comment]
It does work, I've published my changes to https://bintray.com/double16/plugins/fixtures so you can try it if you'd like.

**Comment by 1442acb42ee0e3a727d7330e9755eb94** [comment]
Is this plugin working with Grails 3.3.8?

**Comment by double16** [comment]
> Is this plugin working with Grails 3.3.8?

I'm using my version published on bintray with Grails 3.3.8.

**Comment by 1442acb42ee0e3a727d7330e9755eb94** [comment]
I have added compile 'org.grails.plugins:fixtures:3.0.0.RC2' to build.gradle, but I get the following error. Could you be so kind and give me intructions on how to include it?

Could not find org.grails.plugins:fixtures:3.0.0.RC2.
Searched in the following locations:
    file:/home/tp/.m2/repository/org/grails/plugins/fixtures/3.0.0.RC2/fixtures-3.0.0.RC2.pom
    file:/home/tp/.m2/repository/org/grails/plugins/fixtures/3.0.0.RC2/fixtures-3.0.0.RC2.jar
    https://repo.grails.org/grails/core/org/grails/plugins/fixtures/3.0.0.RC2/fixtures-3.0.0.RC2.pom
    https://repo.grails.org/grails/core/org/grails/plugins/fixtures/3.0.0.RC2/fixtures-3.0.0.RC2.jar

**Comment by double16** [comment]
You need to add the repository to your `build.gradle`:

```groovy
repositories {
    maven { url 'https://dl.bintray.com/double16/plugins' }
}
```

**Comment by 1442acb42ee0e3a727d7330e9755eb94** [comment]
Thank you David for your help. The plugin now gets downloaded.

Do you know how to load test data from a file in the fixtures directory from within BootStrap.groovy for a development environment?

I find the plugin poorly documented. I read the docs at https://github.com/gpc/fixtures/tree/master/src/docs/guide but I can't get it working. 

I tried
```
class BootStrap {

    def fixtureLoader

    def init = { servletContext ->

        environments{
            development{
                fixtureLoader.load("my-test-data.txt") 
            }
            production{
            }
            test{
            }
        }

    }
    def destroy = {
    }
}
```
The fixtureLoader get injected, which is great, but I can't load the test data, because I don't know where to place the my-test-data.txt file.

Also, after downloading the plugin I can't find the "fixtures" directory in the project. It's not being created. Where should I put "my-test-data.txt"?

For which versions of Grails does the project at https://github.com/gpc/fixtures/ work?

**Comment by double16** [comment]
You need to create the `fixtures` directory yourself. I have mine in the root of my Grails project. The fixture data must be a `.groovy` file. I found the documentation to be good, although I'm not sure where it's published now. You could clone this repo and build it. I recommend you try that and read through the docs before trying to get the fixtures loaded.

**Comment by aeischeid** [comment]
When loading up fixtures we get a lot of log noise with this `o.g.c.DefaultGrailsDomainClass The GrailsDomainClass API should no longer be used to retrieve data about domain classes. Use the mapping context API instead`

There is some info about this here http://docs.grails.org/3.3.x/guide/upgrading.html but so far I haven't been able to sort it out.

**Comment by jpalmer1026** [comment]
Looks like the `The GrailsDomainClass API should no longer be used to retrieve data about domain classes. Use the mapping context API instead`message  is being caused by this line in the code: https://github.com/gpc/fixtures/blob/master/src/main/groovy/grails/plugin/fixtures/builder/processor/FixtureBeanPostProcessor.groovy#L57 

That code is calling the DefaultGrailsDomainClass `verifyContextIsInitialized` method, which is logging that method.  Looks like the fix is to inject the `grailsDomainClassMappingContext bean, as outlined towards the bottom on the SO thread: https://stackoverflow.com/questions/4555150/retrieving-a-list-of-gorm-persistent-properties-for-a-domain/4556090

**Comment by aeischeid** [comment]
@jpalmer1026 you had mentioned in a side chat we had that the tests ran ok for you locally. locally I get the same result I am seeing on travis-ci. any thoughts on the tests? 

@double16 for now we are doing some local overrides with modiifed classes from the RC2 build you provided, but if you felt inclined to put an RC3 out on bintray we'd be able to delete those overrides, and that would give me good feels :)

**Comment by double16** [comment]
I am planning on publishing RC3 "soon". Today or tomorrow.

**Comment by jpalmer1026** [comment]
The tests definitely ran (and passed) for me yesterday. I even broke one on purpose to make sure I wasn't getting a false positive. Are you guys getting errors when running them? I'll try again in a few.

**Comment by aeischeid** [comment]
I will try pulling it all fresh and see what I get. I had stuff fairly mangled while I was playing with the multiproject build thing. but last time I tried I got very similar results as here https://travis-ci.org/gpc/fixtures/builds/484325059?utm_source=github_status&utm_medium=notification which they all fail basically because GORM ins't initializing correctly :man_shrugging:

**Comment by double16** [comment]
3.0.0.RC3 published

**Comment by double16** [comment]
I'm also getting the GORM isn't initialized correctly error.

**Comment by aeischeid** [comment]
Just a note that RC3 is working well for me. Still not sure what the deal is with the tests

**Comment by jpalmer1026** [comment]
I'm getting an error as well (`Error Error occurred loading commands: Could not initialize class grails.dev.commands.ApplicationContextCommandRegistry`), but all tests are passing:

```
grails test-app
| Error Error occurred loading commands: org/hibernate/tool/schema/TargetType (Use --stacktrace to see the full trace)
| Error Error occurred loading commands: Could not initialize class grails.dev.commands.ApplicationContextCommandRegistry (Use --stacktrace to see the full trace)
| Error Error occurred loading commands: Could not initialize class grails.dev.commands.ApplicationContextCommandRegistry (Use --stacktrace to see the full trace)
| Error Error occurred loading commands: Could not initialize class grails.dev.commands.ApplicationContextCommandRegistry (Use --stacktrace to see the full trace)
:compileAstJava NO-SOURCE
:compileAstGroovy NO-SOURCE
:processAstResources NO-SOURCE
:astClasses UP-TO-DATE
:compileJava NO-SOURCE
:configScript UP-TO-DATE
:compileGroovy UP-TO-DATE
:copyAstClasses NO-SOURCE
:copyCommands NO-SOURCE
:copyTemplates NO-SOURCE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava NO-SOURCE
:compileTestGroovy NO-SOURCE
:processTestResources NO-SOURCE
:testClasses UP-TO-DATE
:test NO-SOURCE
:compileIntegrationTestJava NO-SOURCE
:compileIntegrationTestGroovy UP-TO-DATE
:processIntegrationTestResources NO-SOURCE
:integrationTestClasses UP-TO-DATE
:integrationTest UP-TO-DATE
:mergeTestReports UP-TO-DATE

BUILD SUCCESSFUL

Total time: 1.037 secs
| Tests PASSED
```

**Comment by aeischeid** [comment]
This plugin is not in fact working yet for mongo domains in grails 3.3 

`grailsDomainClassMappingContext.getPersistentEntity()` returns null for domains that are mapped to mongo, but works as expected for domains that are mapped to hibernate. 

I haven't been able to determine why that would be yet. I wonder if @graemerocher might have some insight on that since it looks like he has worked with that in the mongo plugin itself. https://github.com/grails/gorm-mongodb/commit/312bd3ae2de0632cd3ad5ff0b83b6ccac0febf97

**Comment by jpalmer1026** [comment]
`grailsDomainClassMappingContext` is getting injected into the `FixtureBeanPostProcessor` class. Since the `grailsDomainClassMappingContext` is a `HibernateMappingContext`, the call to `grailsDomainClassMappingContext.getPersistentEntity(instance.getClass().name)` will always return null for mongo instances and they won't get persisted.

The question I'm facing is what can be done to read the entities from both the `HibernateMappingContext` and `MongoMappingContext` instead of only the `HibernateMappingContext`?

**Comment by double16** [comment]
Can you inject both based on type instead of name and then query one, then the other?

**Comment by jpalmer1026** [comment]
With the latest RC4 build, I'm seeing a lot of `Error refresh()ing bean <bean-name> : java.lang.NullPointerException` exceptions when trying to refresh Mongo beans. I'm not sure how big of a deal this actually is, but we should probably have a good look at things before this gets merged into the main plugin branch.

**Comment by aeischeid** [comment]
@jpalmer1026 I put an idea in as code comments on how to resolve that noise. I will try to test that today

**Comment by jpalmer1026** [comment]
@double16, I could inject both, but if there are other mappingContexts besides Hibernate and Mongo, they'll be omitted. I was talking to someone on the Grails forums about the best way to account for this, and he suggested injecting all of the mapping contexts. When I asked if that could be done programmatically, he said it could be done through the applicationContext. Since I didn't see a way to get the mapping contexts through the applicationContext, he asked if I could point him to the code where we're trying to do this, which I did.

After reviewing the code, the reviewer pointed me this [page](https://docs.spring.io/autorepo/docs/spring/4.3.22.RELEASE/javadoc-api/org/springframework/beans/factory/ListableBeanFactory.html#getBeansOfType-java.lang.Class-), but it's still unclear to me how to proceed.

**Comment by aeischeid** [comment]
Just a note for anyone else who might stumble upon this and use this version of the plugin: 3.0.0.RC5 is working really well for us in grails 3.3.9 with mix of hibernate and mongo domains in fixtures. However our mongo domains do NOT use and grails defined associations. For now the plugin basically just skips figuring out associations for non-hibernate domains and tries to save them straight away.

**Comment by spencerpowell** [comment]
@graemerocher @double16 @aeischeid I'm looking to use this plugin and am using Grails 2.5.3.  First of all is this plugin still supported?  And if so where can I find documentation?  When I click the link to the documentation I just get a 404

**Comment by spencerpowell** [comment]
@burtbeckwith @ldaley @hardyrex Maybe one of you might have an answer to the above question as well?  Just trying to see if this plugin is still supported and if there is documentation.  I'm using Grails 2.5.3

**Pull request closed without merging**
